services:

  # gateway:
  #   build: ./gateway
  #   command: npm run dev
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./gateway
  #         target: /app
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: ./gateway/package.json
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - user
  #     - ride
  #     - captain

  ride:
    build: ./ride
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./ride
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./ride/package.json
    ports:
      - "5003:5003"
    env_file:
      - ./ride/.env
    depends_on:
      - mongo
      - kafka
  
  user:
    build: ./user
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./user
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./user/package.json
    ports:
      - "5001:5001"
    env_file:
      - ./user/.env
    depends_on:
      - mongo
      - kafka
  
  captain:
    build: ./captain
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./captain
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./captain/package.json
    ports:
      - "5002:5002"
    env_file:
      - ./captain/.env
    depends_on:
      - mongo
      - kafka
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1